
project:
  type: website
  render:
    - ./posts/
    - ./index.qmd
  preview:
    port: 4200
    browser: true

  # render:
  #   - /index.qmd
  #   - ./posts/2017-04-02-test-deep-sleep-esp8266/index.qmd
  #   - ./posts/2017-04-14-relai-bistable-commande-tension/index.qmd
  #   - ./posts/2016-10-22-esp8266-dht22-oled/index.qmd
  #   - /cours-html-embarque.html
  post-render:
    - ./_scripts/fix_links.py
    - ./_scripts/copy_pages.py

  resources:
      - "./pages/radios/*"

website:
  # reader-mode: true
  # site-path: "/posts/"
  favicon: ./images/favicon.ico
  title: ""
  image: ./images/site-logo.png
  body-footer: "© ouilogique.com"
  search: false
  navbar:
    right:
      - text: "{{< fa regular house >}}"
        file: index.qmd
      - icon: github
        href: https://github.com/NicHub
    # logo: ./images/site-logo.png
    # logo-alt: ouilogique.com
    logo-href: /
    pinned: true
    background: "#1B1B1B"
    collapse: false

  # page-navigation: true
  # sidebar:
  #   style: "floating"
  #   # style: "docked"
  #   search: true
  #   contents: auto
  #   alignment: "center" # "right" "left" # "center"
  #   pinned: false

  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark

  # google-analytics:
  #   tracking-id: "G-2JE1ZVYNWC"

format:
  html:
    theme:
      - cyborg
      - custom.scss
