project:
  type: website
  # render:
  #   - 2014-12-03-manipulation_des_ports/index.qmd

website:
  title: "ouilogique"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cyborg
    css: styles.css
