project:
  type: website
  # render:
  #   - ./index.qmd
  #   - posts/2017-04-02-test-deep-sleep-esp8266/index.qmd
  #   - posts/2017-04-14-relai-bistable-commande-tension/index.qmd
  #   - posts/2016-10-22-esp8266-dht22-oled/index.qmd

website:
  favicon: ./images/favicon.ico
  title: "OUILOGIQUE"
  image: ./images/site-logo.png
  page-navigation: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cyborg
      - custom.scss
