import os

URLS = (
    (
        "https://www.realvnc.com/download/viewer/",
        "https://www.realvnc.com/en/connect/download/viewer/",
    ),
    (
        "https://support.microsoft.com/fr-ch/help/4026635/windows-map-a-network-drive",
        "https://support.microsoft.com/fr-fr/windows/mapper-un-lecteur-r%C3%A9seau-dans-windows-29ce55d1-34e3-a7e2-4801-131475f9557d",
    ),
    (
        "http://www.espressif.com/sites/default/files/9b-esp8266-low_power_solutions_en_0.pdf",
        "https://www.espressif.com/sites/default/files/9b-esp8266-low_power_solutions_en_0.pdf",
    ),
    (
        "http://www.esp8266.com/viewtopic.php?f=13&t=8315",
        "https://www.esp8266.com/viewtopic.php?f=13&t=8315",
    ),
    (
        "http://www.ti.com/lit/ds/symlink/msp430g2453.pdf",
        "https://www.ti.com/lit/ds/symlink/msp430g2453.pdf",
    ),
    (
        "http://www.banggood.com/WeMos-D1-Mini-V2-NodeMcu-4M-Bytes-Lua-WIFI-Internet-Of-Things-Development-Board-Based-ESP8266-p-1115398.html?p=0431091025639201412F",
        "https://usa.banggood.com/D1-Mini-V2-NodeMcu-4M-Bytes-Lua-WIFI-Internet-Of-Things-Development-Board-Based-ESP8266-p-1115398.html?imageAb=2&akmClientCountry=America&p=0431091025639201412F&a=1697372252.7894&akmClientCountry=America",
    ),
    (
        "https://aliexpress.com/af/32818135577.html",
        "https://www.aliexpress.com/af/32818135577.html",
    ),
    (
        "https://www.ni.com/fr-ch/shop/software/products/stewart-platform-trainer-toolkit.html",
        "https://www.ni.com/fr-ch/shop/product/stewart-platform-trainer-toolkit.html",
    ),
    (
        "http://www.robotis.us/dynamixel-mx-64t/",
        "https://www.robotis.us/dynamixel-mx-64t/",
    ),
    (
        "https://aliexpress.com/af/32827461737.html",
        "https://www.aliexpress.com/af/32827461737.html",
    ),
    ("http://www.robotis.us/dynamixel/", "https://www.robotis.us/dynamixel/"),
    (
        "https://aliexpress.com/af/32811563669.html",
        "https://www.aliexpress.us/item/2251832625248917.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    ("http://www.felixros.com/", "https://www.felixros.com/"),
    (
        "https://aliexpress.com/af/32718274859.html",
        "https://www.aliexpress.us/item/2251832531960107.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://www.banggood.com/fr/WeMos-ESP32-WiFi-Bluetooth-Development-Board-Ultra-Low-Power-Consumption-Dual-Core-ESP-32-ESP-32S-p-1175488.html",
        "https://www.banggood.com/fr/ESP32-WiFi-+-bluetooth-Development-Board-Ultra-Low-Power-Consumption-Dual-Core-ESP-32-ESP-32S-Similar-ESP8266-Geekcreit-for-Arduino-products-that-work-with-official-Arduino-boards-p-1175488.html?imageAb=2&akmClientCountry=America",
    ),
    (
        "https://aliexpress.com/af/32887391192.html",
        "https://www.aliexpress.com/af/32887391192.html",
    ),
    (
        "https://aliexpress.com/af/32468820900.html",
        "https://www.aliexpress.us/item/2251832282506148.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "http://emanual.robotis.com/docs/en/platform/openmanipulator/",
        "https://emanual.robotis.com/docs/en/platform/openmanipulator/",
    ),
    (
        "https://www.marginallyclever.com/product/rotary-stewart-platform-v2/",
        "https://www.marginallyclever.com/2013/09/rotary-stewart-platform-v2-now-on-thingiverse/",
    ),
    (
        "https://aliexpress.com/af/32704692789.html",
        "https://www.aliexpress.us/item/2251832518378037.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://01.org/developerjourney/recipe/building-stewart-platform",
        "https://www.intel.com/content/www/us/en/developer/topic-technology/open/overview.html",
    ),
    (
        "https://aliexpress.com/af/32894390128.html",
        "https://www.aliexpress.us/item/2251832708075376.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://aliexpress.com/af/32843432977.html",
        "https://www.aliexpress.com/af/32843432977.html",
    ),
    (
        "https://aliexpress.com/af/32904104171.html",
        "https://www.aliexpress.com/af/32904104171.html",
    ),
    (
        "https://aliexpress.com/af/32809597549.html",
        "https://www.aliexpress.us/item/2251832623282797.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://aliexpress.com/af/32810906485.html",
        "https://www.aliexpress.us/item/2251832624591733.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://www.ni.com/fr-ch/shop/software/products/6-dof-stewart-platform-control-library.html",
        "https://www.ni.com/fr-ch/shop/product/6-dof-stewart-platform-control-library.html",
    ),
    ("http://mikrolar.com/r3000.html", "https://www.mikrolar.com/r3000"),
    (
        "https://fr.aliexpress.com/item//32636102294.html",
        "https://www.aliexpress.us/item/2251832449787542.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://aliexpress.com/af/32775630549.html",
        "https://www.aliexpress.us/item/2251832589315797.html?search_direct=true&spm=a2g0o.productlist.0.0&gatewayAdapt=glo2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/transforming-points-and-vectors",
        "https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/transforming-points-and-vectors.html",
    ),
    (
        "https://www.wolfram.com/training/videos/ENG032/",
        "https://www.wolfram.com/wolfram-u/courses/catalog/",
    ),
    (
        "https://www.realvnc.com/download/viewer/",
        "https://www.realvnc.com/en/connect/download/viewer/",
    ),
    (
        "https://support.microsoft.com/fr-ch/help/4026635/windows-map-a-network-drive",
        "https://support.microsoft.com/fr-fr/windows/mapper-un-lecteur-r%C3%A9seau-dans-windows-29ce55d1-34e3-a7e2-4801-131475f9557d",
    ),
    ("http://dfu-util.sourceforge.net/", "https://dfu-util.sourceforge.net/"),
    (
        "https://developer.mozilla.org/fr/docs/Glossaire/Element_vide",
        "https://developer.mozilla.org/fr/docs/Glossary/Void_element",
    ),
    ("https://unicode-table.com/fr/", "https://symbl.cc/fr/unicode/table/"),
    (
        "https://www.druide.com/fr/enquetes/un-espace-ou-une-espace",
        "https://www.antidote.info/fr/blogue/enquetes/un-espace-ou-une-espace",
    ),
    ("http://brackets.io/", "https://brackets.io/"),
    (
        "http://alistapart.com/article/doctype",
        "https://alistapart.com/article/doctype/",
    ),
    ("https://atom.io/", "https://github.blog/2022-06-08-sunsetting-atom/"),
    (
        "https://www.druide.com/fr/enquetes/apostrophe-et-impostrophe",
        "https://www.antidote.info/fr/blogue/enquetes/apostrophe-et-impostrophe",
    ),
    (
        "https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/let",
        "https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/let",
    ),
    (
        "https://developer.mozilla.org/fr/docs/Web/JavaScript/Une_r%C3%A9introduction_%C3%A0_JavaScript",
        "https://developer.mozilla.org/fr/docs/Web/JavaScript/Language_overview",
    ),
    (
        "http://stackoverflow.com/a/17218003/3057377",
        "https://stackoverflow.com/questions/4228356/how-to-perform-an-integer-division-and-separately-get-the-remainder-in-javascr/17218003#17218003",
    ),
    ("http://jsfiddle.net/Ac6CT/", "https://jsfiddle.net/Ac6CT/"),
    ("https://unicode-table.com/fr/", "https://symbl.cc/fr/unicode/table/"),
    (
        "https://www.druide.com/fr/enquetes/un-espace-ou-une-espace",
        "https://www.antidote.info/fr/blogue/enquetes/un-espace-ou-une-espace",
    ),
    (
        "https://developer.mozilla.org/fr/docs/Glossaire/Element_vide",
        "https://developer.mozilla.org/fr/docs/Glossary/Void_element",
    ),
    ("https://atom.io/", "https://github.blog/2022-06-08-sunsetting-atom/"),
    (
        "https://www.druide.com/fr/enquetes/apostrophe-et-impostrophe",
        "https://www.antidote.info/fr/blogue/enquetes/apostrophe-et-impostrophe",
    ),
    (
        "http://alistapart.com/article/doctype",
        "https://alistapart.com/article/doctype/",
    ),
    ("http://brackets.io/", "https://brackets.io/"),
    (
        "https://developers.google.com/speed/pagespeed/insights/?hl=fr",
        "https://pagespeed.web.dev/?utm_source=psi&utm_medium=redirect&hl=fr",
    ),
    ("https://foundation.zurb.com/", "https://get.foundation/"),
    (
        "https://developer.mozilla.org/fr/docs/Web/CSS/Requ%C3%AAtes_m%C3%A9dia/Utiliser_les_Media_queries",
        "https://developer.mozilla.org/fr/docs/Web/CSS/CSS_media_queries/Using_media_queries",
    ),
    ("http://sass-lang.com/", "https://sass-lang.com/"),
    (
        "http://www.lepetitvapoteur.com/fr/accus/1876-accu-mxjo-imr-18650-3000-ma-35-a-.html",
        "https://www.lepetitvapoteur.com/fr/accus/1876-accu-mxjo-imr-18650-3000-ma-35-a-.html",
    ),
    (
        "https://core-electronics.com.au/tutorials/stress-testing-your-raspberry-pi.html",
        "https://core-electronics.com.au/guides/stress-testing-your-raspberry-pi/",
    ),
    (
        "http://lists.alioth.debian.org/pipermail/pkg-phototools-devel/2017-June/010392.html",
        "https://alioth-lists.debian.net/pipermail/pkg-phototools-devel/2017-June/010392.html",
    ),
    (
        "http://www.ikalogic.com/ikalogic-products/scanalogic-2/",
        "https://www.ikalogic.com/ikalogic-products/scanalogic-2/",
    ),
    ("https://didel.ch/", "https://www.didel.com/"),
    (
        "http://www.raytac.com/download/MDBT40/MDBT40%20spec-Version%20A3.pdf",
        "https://www.raytac.com/download/MDBT40/MDBT40%20spec-Version%20A3.pdf",
    ),
    ("http://redbearlab.com/nrf51822/", "https://redbear.cc/particle"),
    (
        "http://www.banggood.com/HM-10-Bluetooth-4_0-Module-Transparent-Serial-Port-p-967059.html?p=0431091025639201412F",
        "https://www.banggood.com/sitemap.html",
    ),
    (
        "http://www.microchip.com/wwwproducts/Devices.aspx?product=bm77",
        "https://www.microchip.com/",
    ),
    (
        "http://fr.aliexpress.com/item/Low-power-consumption-BLE4-0-module-with-2-4GHz-PCB-antenna16-28mm-Free-sample/32334323347.html",
        "https://www.aliexpress.us/item/2251832148008595.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://developer.apple.com/hardwaredrivers/BluetoothDesignGuidelines.pdf",
        "https://developer.apple.com/accessories/Accessory-Design-Guidelines.pdf",
    ),
    ("http://www.dfrobot.com/", "https://www.dfrobot.com/"),
    (
        "http://fr.aliexpress.com/item/DFRoBot-100-Original-DIY-Bluno-Beetle-V1-0-wearable-mini-Micro-main-controller-Board-with-Bluetooth/32456535853.html",
        "https://www.aliexpress.us/item/2251832270221101.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "http://www.banggood.com/NRF51822-2_4GHz-Network-Bluetooth-Serial-Module-Support-For-Apple-Android-p-992468.html?p=0431091025639201412F",
        "https://www.banggood.com/sitemap.html",
    ),
    ("https://github.com/sandeepmistry/noble", "https://github.com/noble/noble"),
    (
        "http://playground.arduino.cc/Main/I2cScanner",
        "https://playground.arduino.cc/Main/I2cScanner",
    ),
    (
        "http://www.banggood.com/4-in-1-Temperature-Pressure-Altitude-Light-Sensor-Module-p-965547.html?p=0431091025639201412F",
        "https://www.banggood.com/sitemap.html",
    ),
    (
        "https://github.com/adafruit/Touch-Screen-Library",
        "https://github.com/adafruit/Adafruit_TouchScreen",
    ),
    (
        "http://arduino.stackexchange.com/a/31417/13995",
        "https://arduino.stackexchange.com/questions/31413/arrange-vector-in-descending-order/31417#31417",
    ),
    (
        "https://www.fontyukle.net/en/DownLoad-Graphite+Std.ttf",
        "https://www.fontyukle.net/downloadfont/Graphite%20Std",
    ),
    ("http://www.diveintopython3.net/", "https://diveintopython3.net/"),
    (
        "https://fr.aliexpress.com/item/laptop-High-Speed-blue-USB-3-0-cable-A-Female-TO-A-Female-Adapter-cables-converter/1855157465.html",
        "https://www.aliexpress.us/item/2251801668842713.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://fr.aliexpress.com/item/2014-newest-7-Port-USB-3-0-HUB-High-Speed-With-Power-Adapter-For-Laptop-Notebook/1997348166.html",
        "https://www.aliexpress.us/item/2251801811033414.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://www.delock.de/produkte/S_61857/merkmale.html",
        "https://www.delock.de/produkt/61857/merkmale.html?f=s",
    ),
    (
        "https://www.adafruit.com/blog/2011/11/18/adafruit-perma-proto-half-sized-breadboard-pcb-3-pack/",
        "https://blog.adafruit.com/2011/11/18/adafruit-perma-proto-half-sized-breadboard-pcb-3-pack/",
    ),
    (
        "https://www.adafruit.com/datasheets/WS2812.pdf",
        "https://cdn-shop.adafruit.com/datasheets/WS2812.pdf",
    ),
    (
        "http://www.miniinthebox.com/fr/programme-downloader-ftdi-basic-usb-a-ttl-ft232-pour-arduino_p903425.html",
        "https://m.miniinthebox.com/fr/p/programme-downloader-ftdi-basic-usb-a-ttl-ft232-pour-arduino_p903425.html",
    ),
    (
        "https://fr.aliexpress.com/item/50pcs-1N4004-400V-1A-DO-41-Axial-Lead-Silicon-Rectifier-Diodes/32464825368.html",
        "https://www.aliexpress.us/item/2251832278510616.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "http://www.banggood.com/20pcs-2-Pin-Plug-in-Screw-Terminal-Block-Connector-5_08mm-Pitch-p-993197.html?p=0431091025639201412F",
        "https://usa.banggood.com/20pcs-2-Pin-Plug-In-Screw-Terminal-Block-Connector-5_08mm-Pitch-p-993197.html?imageAb=1&akmClientCountry=America&p=0431091025639201412F&a=1697373192.6246&akmClientCountry=America",
    ),
    (
        "https://fr.aliexpress.com/item/Free-shippin-10pcs-lot-SFH620A-DIP-DIP-4-new-original/32553455903.html?spm=2114.13010608.0.0.H1VvjL",
        "https://www.aliexpress.us/item/2251832367141151.html?spm=2114.13010608.0.0.H1VvjL&gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://fr.aliexpress.com/item/PG7-Cable-Glands-Nylon-plastic-waterproof-cable-connectors-spiral-fixed-2013-New-product/1000045565.html",
        "https://www.aliexpress.us/item/2251800813730813.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://fr.aliexpress.com/item/Two-colors-plastic-enclosure-diy-project-box-abs-plastic-box-electronics-small-desktop-box-135/32426076659.html",
        "https://www.aliexpress.us/item/2251832239761907.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://fr.aliexpress.com/item/3pcs-HSS-Steel-Step-Cone-Milling-Cutter-Titanium-Coated-Step-Drill-Cutting-Tools-Bit-Set/32661376446.html",
        "https://www.aliexpress.us/item/2251832475061694.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://fr.aliexpress.com/item/10-sets-5-08-2pin-Right-angle-Terminal-plug-type-300V-10A-5-08mm-pitch-connector/32787731420.html",
        "https://www.aliexpress.us/item/2251832601416668.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://fr.aliexpress.com/item/Industrial-FOTEK-single-phase-solid-state-relay-SSR-25DA-25A-actually-3-32V-DC-TO-24/32621331021.html",
        "https://www.aliexpress.us/item/2251832435016269.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "https://fr.aliexpress.com/item/F217-10-sets-ht5-08-3pin-Terminal-plug-type-300V-10A-5-08mm-pitch-connector-pcb/32657384224.html",
        "https://www.aliexpress.us/item/2251832471069472.html?gatewayAdapt=fra2usa4itemAdapt&_randl_shipto=US",
    ),
    (
        "http://www.banggood.com/5Pcs-3_3V-8MHz-ATmega328P-AU-Pro-Mini-Microcontroller-Board-For-Arduino-p-980292.html?p=0431091025639201412F",
        "https://usa.banggood.com/5Pcs-3_3V-8MHz-ATmega328P-AU-Pro-Mini-Microcontroller-With-Pins-Development-Board-p-980292.html?imageAb=2&akmClientCountry=America&p=0431091025639201412F&a=1697373190.4133&akmClientCountry=America",
    ),
    (
        "http://arduino.stackexchange.com/questions/18575/send-at-commands-to-esp8266-from-arduino-uno-via-a-softwareserial-port/18614",
        "https://arduino.stackexchange.com/questions/18575/send-at-commands-to-esp8266-from-arduino-uno-via-a-softwareserial-port/18614",
    ),
    (
        "https://learn.adafruit.com/system/assets/assets/000/023/769/original/led_matrix_socket3.png?1426305755",
        "https://cdn-learn.adafruit.com/assets/assets/000/023/769/original/led_matrix_socket3.png?1426305755",
    ),
)

SOURCE_PATH_POSTS = os.path.expanduser("~/kdnicomac/sites/ouilogique.com/_posts/")

files = sorted(os.listdir(SOURCE_PATH_POSTS), reverse=True)
for file in files:
    fpath = f"{SOURCE_PATH_POSTS}{file}"
    with open(fpath, "rt", encoding="utf-8") as _f:
        content = _f.read()
    for url in URLS:
        content = content.replace(url[0], url[1])
    with open(fpath, "wt", encoding="utf-8") as _f:
        _f.write(content)
